name: Node.js CI

on: pull_request

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
            - name: Deploy to chromatic
              run: |
                  npm install
                  npx chromatic --project-token $CHROMATIC_TOKEN --exit-zero-on-changes
              env:
                  CHROMATIC_TOKEN: ${{ secrets.CHROMATIC }}
