name: Node.js CI

on: pull_request

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  always-auth: true
                  node-version: '16.x'
                  registry-url: https://npm.pkg.github.com/
                  scope: '@dassana-io'
            - name: Run install, lint, and build
              run: |
                  npm install --legacy-peer-deps
                  npx eslint src --ext js,jsx,ts,tsx --report-unused-disable-directives --max-warnings 0
                  npm run build
              env:
                  CI: true
                  FONT_AWESOME_AUTH_TOKEN: ${{ secrets.FONT_AWESOME_AUTH_TOKEN }}
                  NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
